import Header from '@/components/Nav'
import Providers from '@/components/Providers/Providers'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer'

const montserrat = Montserrat({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'And Tex',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <Header />
        <main className="flex flex-col min-h-[calc(100vh-6.8rem-1px)]">
          <div className="flex bg-slate-50 flex-1 h-full flex-col">
            <Providers>{children}</Providers>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  )
}
